### ISSUE TITLE
Feasible to support during invoke local

### ISSUE THREAD

**Issue by tbrannam** [zaru/serverless-plugin-embedded-env-in-code#1]
Thanks for solving for this.  Is if feasible to have the plugin either do the substitution into the environment when executing sls invoke local?  The alternative appears to be to maintain the same value in two locations

```
functions:
 myfunc:
   ....
   embedded:
      files:
        - src/env.js
      variables:
        DB_TABLE_NAME: ${self:custom.dynamoDBTable}
    environment:
      DB_TABLE_NAME: ${self:custom.dynamoDBTable}
```
